<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-Notes/blob/main/Numpy/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#np.array
#1D array
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#2D and 3D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#dtype
z = np.array([1,2,3],dtype = float)
print(z)

[1. 2. 3.]


In [ ]:
#np.arange
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# With reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# np.ones and np.zeros
a = np.ones((3,3))
b = np.zeros((3,3))
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.random
np.random.random((3,3))

array([[0.31445361, 0.07832137, 0.9002566 ],
       [0.36592904, 0.76361587, 0.18901199],
       [0.95474794, 0.10187089, 0.03146855]])

In [ ]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim
a1.ndim

1

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a3.shape)
print(a3.size)

(2, 2, 2)
8


In [ ]:
# itemsize
a3.itemsize
print(a2.itemsize)

8


In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [ ]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
print(a1 * 2)
print(a2 + 2)
print(a1 ** 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
# relational
print(a2 > 5)
print(a1 > 4)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [ ]:
# vector operations
# arithmetic
print(a1 + a2)
print(a1 * a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


# Array Functions

In [ ]:
import numpy as pd
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[43.,  2., 80.],
       [94., 54., 99.],
       [80., 80., 78.]])

In [ ]:
# max/min/sum/prod(multiplication)
# 0 -> col and 1 -> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.max(a1,axis = 1))#(row wise maximum number)
print(np.max(a1,axis = 0))#(column wise maximum number)
#

99.0
2.0
610.0
1725916667904000.0
[80. 99. 80.]
[94. 80. 99.]


In [ ]:
# mean/median/std/var
print(np.mean(a1))

67.77777777777777


In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,a3))


[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))

[[3.76120012 0.69314718 4.38202663]
 [4.54329478 3.98898405 4.59511985]
 [4.38202663 4.38202663 4.35670883]]
[[4.72783947e+18 7.38905610e+00 5.54062238e+34]
 [6.66317622e+40 2.83075330e+23 9.88903032e+42]
 [5.54062238e+34 5.54062238e+34 7.49841700e+33]]


In [ ]:
# round,floor
np.round(np.random.random((2,3)))*100
np.floor(np.random.random((2,3)))*100

array([[100., 100.,   0.],
       [  0.,   0., 100.]])

# Indexing and Slicing

In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a2[1,2]) # (a2[row,col])

6


In [ ]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(a3[1,0,1]) # a3[dim,row,com]

5


In [ ]:
# slicing
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a1[2:5])

[2 3 4]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a2[0,:])
print(a2[:,2]) # a2[row,col(':' means all)]
print(a2[1,::3])

[0 1 2 3]
[ 2  6 10]
[4 7]


In [ ]:
# Slicing to get 5, 6, 9, 10 from a2
# Row 1 and 2, Column 1 and 2
print(a2[1:3, 1:3])

[[ 5  6]
 [ 9 10]]


In [ ]:
# Iterating

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


# Reshaping

In [ ]:
#transpose
np.transpose(a2)
print(a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#ravel
print(a2.ravel()) #convert to 1D array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking

In [ ]:
# Example of Horizontal Stacking
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)

print('Array A:\n', a)
print('Array B:\n', b)

print('\nHorizontal Stack:')
print(np.hstack((a, b)))

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Example of Vertical Stacking
print('Vertical Stack:')
print(np.vstack((a, b)))

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting

In [ ]:
import numpy as np
# Create a 4x4 array for splitting
a = np.arange(16).reshape(4,4)
print('Original Array:\n', a)

# Horizontal splitting (splitting columns into equal parts)
# This splits the 4x4 into two 4x2 arrays
print('\nHorizontal Split (into 2):')
print(np.hsplit(a, 2))

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontal Split (into 2):
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
import numpy as np
# Vertical splitting (splitting rows into equal parts)
# This splits the 4x4 into two 2x4 arrays
print('Vertical Split (into 2):')
print(np.vsplit(a, 2))

Vertical Split (into 2):
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
